CREATE TABLE ACCOUNT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    BALANCE DECIMAL(9,2) NOT NULL,
    ACCOUNT_NUMBER VARCHAR(11) NOT NULL
);

CREATE TABLE HISTORY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_NUMBER VARCHAR(11) NOT NULL,
    TRANSACTION_TYPE VARCHAR(8) NOT NULL,
    DATE_TRANSACTION DATE NOT NULL,
    TRANSACTION_AMOUNT DECIMAL(9,2) NOT NULL
);
